import type { Metadata } from "next";
import type { CSSProperties } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import "@fontsource/delius/400.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/300.css";
import { ParticlesBackground } from "@/components/particles-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootHtmlStyle = CSSProperties & {
  "--font-header": string;
  "--font-body": string;
};

const rootHtmlStyle: RootHtmlStyle = {
  "--font-header": "Delius, cursive",
  "--font-body": "Inter, sans-serif",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={rootHtmlStyle}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-body`}>
        <ThemeProvider>
          <Navbar />
          <ParticlesBackground />
          <div className="relative z-10 pt-16">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
